# This script will implement the Tier 5 meta-labeling pipeline.

import os
import sys
import pandas as pd
import lightgbm as lgb
import numpy as np
import time

# Add the project root to the Python path to enable imports from 'src'
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from src.tier1.modeling.train_xgboost import get_tri_barrier_labels
from src.tier2.backtester import VectorizedBacktester
from src.tier2.strategy_overlay import StrategyOverlay
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

def train_primary_model(test_size=0.2):
    """
    Loads data, trains the primary (high-recall) model, and generates
    out-of-sample predictions.
    """
    print(f"[{time.ctime()}] --- Training Primary Model ---")

    # 1. Load Data
    PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    FEATURE_PATH = os.path.join(PROJECT_ROOT, 'data/processed/features_v2_final.parquet')
    df = pd.read_parquet(FEATURE_PATH)

    # 2. Create Tri-Barrier Labels (the actual trade outcomes)
    df['outcome'] = get_tri_barrier_labels(df['btc_close'])
    df = df.dropna(subset=['outcome'])

    # 3. Define Features (X) and Target for Primary Model (y_primary)
    # The primary model predicts the *direction* of the trade.
    y_primary = df['outcome'].copy()
    y_primary[y_primary == -1] = 0 # Map sell signals to 0 for binary classification vs. buy (1)

    features_to_exclude = ['btc_close', 'eur_close', 'gld_close', 'btc_volume', 'eur_volume', 'gld_volume', 'event_name', 'outcome']
    features = [c for c in df.columns if c not in features_to_exclude]
    X = df[features]

    # 4. Chronological Split
    split_index = int(len(df) * (1 - test_size))
    X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
    y_train, y_test = y_primary.iloc[:split_index], y_primary.iloc[split_index:]

    # Also keep the original outcomes for the test set, as we'll need them to create meta-labels
    outcomes_test = df['outcome'].iloc[split_index:]

    # 5. Train LightGBM Model
    # Note: For simplicity here, we use a simple binary classifier (buy vs. not buy).
    # This could be expanded to multiclass, but binary is a good start for meta-labeling.
    params = {
        'objective': 'binary', 'metric': 'binary_logloss', 'boosting_type': 'gbdt',
        'num_leaves': 31, 'learning_rate': 0.05, 'feature_fraction': 0.9,
        'verbose': -1, 'seed': 42
    }
    model = lgb.LGBMClassifier(**params)
    model.fit(X_train, y_train)

    # 6. Generate Predictions
    df_test = df.iloc[split_index:].copy()
    df_test['primary_prediction'] = model.predict(X_test)

    print(f"[{time.ctime()}] --- Primary Model Training Complete ---")
    return df_test


def generate_meta_labels(predictions_df):
    """
    Generates meta-labels based on the primary model's predictions.
    A meta-label is 1 if the primary model's prediction was correct, 0 otherwise.
    """
    print(f"[{time.ctime()}] --- Generating Meta-Labels ---")

    # We only care about the cases where the primary model predicted a "buy"
    predictions_df['meta_label'] = 0

    # Get indices where primary model predicted a buy
    buy_indices = predictions_df[predictions_df['primary_prediction'] == 1].index

    # For those predictions, the meta-label is 1 if the actual outcome was also a buy (1)
    correct_predictions = predictions_df.loc[buy_indices]
    correct_predictions = correct_predictions[correct_predictions['outcome'] == 1]

    predictions_df.loc[correct_predictions.index, 'meta_label'] = 1

    print("Meta-label distribution:")
    print(predictions_df.loc[buy_indices, 'meta_label'].value_counts())

    print(f"[{time.ctime()}] --- Meta-Label Generation Complete ---")
    return predictions_df

def train_meta_model(predictions_df):
    """
    Trains the secondary (meta) model to predict the outcome of the primary model.
    """
    print(f"[{time.ctime()}] --- Training Meta Model ---")

    # 1. Define Feature Set (X) and Meta Target (y_meta)
    features_to_exclude = ['btc_close', 'eur_close', 'gld_close', 'btc_volume', 'eur_volume', 'gld_volume',
                             'event_name', 'outcome', 'primary_prediction', 'meta_label']
    features = [c for c in predictions_df.columns if c not in features_to_exclude]

    # The meta-model is only trained on the signals generated by the primary model
    primary_signals = predictions_df[predictions_df['primary_prediction'] == 1]
    X_meta_train = primary_signals[features]
    y_meta_train = primary_signals['meta_label']

    # 2. Handle Class Imbalance
    classes = np.unique(y_meta_train)
    weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_meta_train)
    class_weight_dict = dict(zip(classes, weights))

    # 3. Train LightGBM Meta-Model
    params = {
        'objective': 'binary', 'metric': 'binary_logloss', 'boosting_type': 'gbdt',
        'num_leaves': 15, 'learning_rate': 0.05, 'feature_fraction': 0.8,
        'verbose': -1, 'seed': 1337, 'class_weight': class_weight_dict
    }
    meta_model = lgb.LGBMClassifier(**params)
    meta_model.fit(X_meta_train, y_meta_train)

    # 4. Generate Meta-Predictions
    # Predict the probability of the primary signal being correct
    X_test_all = predictions_df[features]
    predictions_df['meta_prediction'] = meta_model.predict_proba(X_test_all)[:, 1]

    print(f"[{time.ctime()}] --- Meta Model Training Complete ---")
    return predictions_df

def generate_final_signals(predictions_df, confidence_threshold=0.7):
    """
    Generates the final trading signals based on the meta-model's confidence.
    """
    print(f"[{time.ctime()}] --- Generating Final, Filtered Signals ---")

    # Start with a neutral signal (hold)
    predictions_df['final_signal'] = 0

    # A "buy" signal is only generated if the primary model says "buy" AND
    # the meta-model's confidence is above the threshold.
    condition_buy = (predictions_df['primary_prediction'] == 1) & (predictions_df['meta_prediction'] > confidence_threshold)
    predictions_df.loc[condition_buy, 'final_signal'] = 1

    print(f"Final signal counts (Threshold={confidence_threshold}):")
    print(predictions_df['final_signal'].value_counts())

    print(f"[{time.ctime()}] --- Final Signal Generation Complete ---")
    return predictions_df

def backtest_meta_strategy(predictions_df, transaction_cost=0.001):
    """
    Backtests the final, meta-labeled trading strategy.
    """
    print(f"[{time.ctime()}] --- Backtesting Meta-Labeled Strategy ---")

    # 1. Define Paths & Extract Data
    PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'analysis/backtest_reports')
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    price_data = predictions_df['btc_close']
    signals = predictions_df['final_signal']

    # 2. Initialize Strategy Overlay and Backtester
    strategy_overlay = StrategyOverlay(price_data=price_data, volatility_lookback=21, volatility_target=0.02)
    backtester = VectorizedBacktester(price_data=price_data,
                                      signals=signals,
                                      initial_capital=100000,
                                      strategy_overlay=strategy_overlay,
                                      transaction_cost=transaction_cost)

    # 3. Generate and Print Performance Report
    print(f"\n--- Backtest Performance: Meta-Labeled Strategy ---")
    metrics = backtester.get_performance_metrics()
    for key, value in metrics.items():
        print(f"{key}: {value:.4f}")
    print("--------------------------------------------------\n")

    # 4. Save Equity Curve
    plot_path = os.path.join(OUTPUT_DIR, "tier5_meta_labeled_equity_curve.png")
    backtester.plot_equity_curve(plot_path)

    print(f"[{time.ctime()}] --- Backtesting Complete ---")
    return metrics

def main():
    """
    Main function to run the meta-labeling pipeline.
    """
    print(f"[{time.ctime()}] --- Starting Tier 5 Meta-Labeling Pipeline ---")

    # 1. Train primary model and get its predictions
    predictions_df = train_primary_model()

    # 2. Generate meta-labels
    predictions_df = generate_meta_labels(predictions_df)

    # 3. Train the meta-model to predict the primary model's success
    predictions_df = train_meta_model(predictions_df)

    # 4. Generate the final, high-precision signals
    predictions_df = generate_final_signals(predictions_df)

    # 5. Backtest the final strategy
    backtest_meta_strategy(predictions_df)

    print(f"[{time.ctime()}] --- Meta-Labeling Pipeline Finished ---")

if __name__ == '__main__':
    main()
